# Generated by Django 4.1.6 on 2023-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_id_task_id_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_task',
            new_name='id',
        ),
    ]
