# Generated by Django 4.1.4 on 2023-01-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=255)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('lyrics', models.TextField(blank=True)),
            ],
        ),
    ]
